spring:
  application:
    name: sutpc-algo-server
  profiles:
    active: dev
  datasource:
    name: dev
    url: jdbc:postgresql://10.10.201.2:30001/transpaas_mp_algo
    username: postgres
    password: TestBGLech0^Wa
    # \u4F7F\u7528druid\u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
server:
  port: 8080
#eureka:
#  client:
#    service-url:
#      defaultZone: http://10.10.38.110:8801/eureka
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  # MapperXml\u4E2D\u5B9E\u4F53\u7C7B\u522B\u540D
  type-aliases-package: com.sutpc.transpaas.algoserver.*.entity
  global-config:
    db-config:
      id-type: uuid
      logic-delete-value: '1'
      logic-not-delete-value: '0'
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
