
spring:
  profiles:
    active: dev
  datasource:
    name: dev
    url: jdbc:postgresql://10.10.201.2:30001/transpaas_mp_algo
    username: postgres
    password: TestBGLech0^Wa
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 18080
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.sutpc.transpaas.algoserver.*.entity
  global-config:
    db-config:
      id-type: uuid
      logic-delete-value: '1'
      logic-not-delete-value: '0'
logging:
  config: classpath:logback.xml
  level:
    root: info
client:
  taskFlag: true
  #modelInputFile: /home/app/sutpc-algo-server/ModelInputFile
  #modelOutputFile: /home/app/sutpc-algo-server/ModelOutputFile
  modelOutputFile: D:\model_output
  modelInputFile: D:\model_input
  standardTaskId: 50796ce2f4d94c74a6f3df5686ff975a
  omxUrl: 10.10.49.74:8090
ftp:
  host: 10.10.10.4
  port: 1004
  username: model_wuhan
  password: Sutpc@wuhan
  #是否被动模式
  passiveMode: true